import { Navbar, Footer } from "@/components";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

export const metadata = {
  title: "RideRover Car Rental",
  description: "Generated by create next app",
};

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} relative`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
